image: registry.git.rzc.fr/marc/docker-images/java-builder-8:latest

stages:
  - "build"
  - "test"
  - "publish"

build:
  stage: build
  script: ./gradlew assemble --info --stacktrace
  cache:
    - key: "$CI_COMMIT_REF_NAME"
      policy: push
      paths:
        - "**/build"
        - /home/builder/.gradle

test:
  stage: test
  script: ./gradlew check --info --stacktrace
  artifacts:
    when: always
    reports:
      junit: "**/build/test-results/*/**/TEST-*.xml"
  cache:
    - key: "$CI_COMMIT_REF_NAME"
      paths:
        - "**/build"
        - /home/builder/.gradle

publish:
  stage: publish
  script: ./gradlew publishPlugins "-Pgradle.publish.key=$GRADLE_PUBLISH_KEY" "-Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET" --info --stacktrace
  cache:
    - key: "$CI_COMMIT_REF_NAME"
      paths:
        - "**/build"
        - /home/builder/.gradle
