---
preset: simple
releaseAssets:
  helm-plugin:
    fileName: "helm-plugin"
    description: "helm-publish-plugin {{version}}"
    type: "application/octet-stream"
    path: "helm-plugin/build/libs/"
  helm-publish-plugin:
    fileName: "helm-publish-plugin"
    description: "helm-publish-plugin {{version}}"
    type: "application/octet-stream"
    path: "helm-publish-plugin/build/libs/"
  helm-releases-plugin:
    fileName: "helm-releases-plugin"
    description: "helm-releases-plugin {{version}}"
    type: "application/octet-stream"
    path: "helm-releases-plugin/build/libs/"
commitMessageConventions:
  enabled:
    - conventionalCommits
  items:
    conventionalCommits:
      expression: "(?m)^(?<type>[a-zA-Z0-9_]+)(!)?(\\((?<scope>[a-z ]+)\\))?:( (?<title>.+))$(?s).*"
      bumpExpressions:
        major: "(?s)(?m)^[a-zA-Z0-9_]+(!|.*^(BREAKING( |-)CHANGE: )).*"
        minor: "(?s)(?m)^feat(?!!|.*^(BREAKING( |-)CHANGE: )).*"
        patch: "(?s)(?m)^fix(?!!|.*^(BREAKING( |-)CHANGE: )).*"
git:
  remotes:
    origin:
      authenticationMethod: USER_PASSWORD
      user: "{{#environmentVariable}}GH_TOKEN{{/environmentVariable}}"
      password: ""
changelog:
  path: "build/CHANGELOG.md"
  template: ".github/CHANGELOG.tpl"
  sections:
    "Added": "^feat$"
    "Fixed": "^fix$"
  substitutions:
    "(?m)#([0-9]+)(?s)": "[#%s](https://github.com/mehmetsalgar/gradle-helm-plugin/issues/%s)"
releaseTypes:
  enabled:
    - mainline
    - internal
  publicationServices:
    - github
  items:
    mainline:
      collapseVersions: false
      filterTags: "^()?([0-9]\\d*)\\.([0-9]\\d*)\\.([0-9]\\d*)$"
      gitCommit: "true"
      gitCommitMessage: "Release version "
      gitPush: "true"
      gitTag: "true"
      gitTagMessage: "Tag release "
      matchBranches: "^(master|main)$"
      matchEnvironmentVariables:
        CI: "^true$"
      matchWorkspaceStatus: "CLEAN"
      publish: "true"
      versionRangeFromBranchName: false
    internal:
      collapseVersions: false
      collapsedVersionQualifier: "internal"
      description: "Internal release "
      filterTags: "^()?([0-9]\\d*)\\.([0-9]\\d*)\\.([0-9]\\d*)$"
      gitCommit: "false"
      gitPush: "false"
      gitTag: "false"
      identifiers:
        - qualifier: "{{#sanitizeLower}}{{branch}}{{/sanitizeLower}}"
          position: "BUILD"
        - qualifier: "{{#short5}}{{releaseScope.finalCommit}}{{/short5}}"
          position: "BUILD"
        - qualifier: "{{#timestampYYYYMMDDHHMMSS}}{{timestamp}}{{/timestampYYYYMMDDHHMMSS}}"
          position: "BUILD"
          value: ""
      publish: "false"
      versionRangeFromBranchName: false
scheme: "SEMVER"
releaseLenient: true
releasePrefix: ""
services:
  github:
    type: "GITHUB"
    options:
      # The GH_TOKEN variable is fetched from the "secrets" context and passed as an environment variable.
      # See:
      # - https://docs.github.com/en/actions/security-guides/automatic-token-authentication
      # - https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
      AUTHENTICATION_TOKEN: "{{#environmentVariable}}GH_TOKEN{{/environmentVariable}}"
      REPOSITORY_NAME: "gradle-helmng-plugin"
      REPOSITORY_OWNER: "bullshit"
resume: true
stateFile: "build/.nyx-state.yml"
verbosity: DEBUG
