---
preset: simple
services:
  github:
    type: "GITHUB"
    options:
      # The GH_TOKEN variable is fetched from the "secrets" context and passed as an environment variable.
      # See:
      # - https://docs.github.com/en/actions/security-guides/automatic-token-authentication
      # - https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
      AUTHENTICATION_TOKEN: "{{#environmentVariable}}GH_TOKEN{{/environmentVariable}}"
      REPOSITORY_NAME: "gradle-helmng-plugin"
      REPOSITORY_OWNER: "bullshit"
#resume: true
#stateFile: ".nyx-state.json"